name: Build and Cache

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-latest
            system: aarch64-darwin
          - runner: ubuntu-latest
            system: x86_64-linux
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: cachix/cachix-action@v15
        with:
          name: sushruth-nix-php56
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#packages.${{ matrix.system }}.php56
        env:
          NIX_CONFIG: sandbox = false
